### ISSUE TITLE
seek before video loaded issue

### ISSUE THREAD

**Issue by zezo357** [alexmercerind/dart_vlc#166] opened 2021-09-28 12:06 UTC
the video player gets stuck if seek is called before the network video is loaded
and doesn't produce any errors

as a work around I made the code check the duration of the video before seeking if 0 seconds then the video is not loaded if more then its loaded

hope it can be fixed

**Comment by alexmercerind** [comment] 2021-09-28 12:08
Duplicate of #126. I will create a new release after adding that feature. Sorry for the delay.

**Closed by alexmercerind** 2021-09-28 12:08 UTC

**Comment by zezo357** [comment] 2021-09-28 12:14
its okay, thanks for your work
