### ISSUE TITLE
Calling player.insert(index, media) multiple times causes player.current.media mismatch

### ISSUE THREAD

**Issue by Martini765** [alexmercerind/dart_vlc#161] opened 2021-09-24 00:32 UTC
### Flutter doctor
`Doctor summary (to see all details, run flutter doctor -v):`
`[✓] Flutter (Channel stable, 2.5.0, on Manjaro Linux 5.4.144-1-MANJARO, locale pt_BR.UTF-8)`
`[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)`
`[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)`
`    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.`
`[✓] Linux toolchain - develop for Linux desktop`
`[✓] Android Studio (version 2020.3)`
`[✓] Connected device (1 available)`
`! Doctor found issues in 1 category.`

### Expected behavior
Inserting multiple medias should not change the current index and media of a playlist.

### Current behavior
Say that the current index and media are 10 and media10 (playlist), inserting multiple medias at index 11 (currentIndex + 1) causes the current media to advance by 1 each time: media11, media12...

### Possible cause
[This line seems to be the problem](https://github.com/alexmercerind/dart_vlc/blob/3f8c73d094548cca3cc7a9cc837303ec05f04205/dartvlc/internal/setters.h#L166)
By removing it, player.insert works as expected.

**Comment by krjw-eyev** [comment] 2021-09-26 10:08
Could this change have any sideaffects @alexmercerind? I am unfamiliar with the cpp part of this project. If not you could easily submit a pr @Martini765.

**Comment by alexmercerind** [comment] 2021-09-26 10:13
@krjw-eyev being able to manage the playlist i.e. adding/inserting/moving etc. is not a feature of libVLC itself, and technically that line which @Martini765 tagged is correct because if media is inserted before current position, the index should in-fact increase.

I'm not sure about this, I'm not targeting this as high-priority either. Will see, most likely a logical error or something. Users can themselves implement or improve existing playlist system.

**Comment by alexmercerind** [comment] 2022-04-08 15:23
Closing issue due to no recent update or reproducibility in current version.

**Closed by alexmercerind** 2022-04-08 15:23 UTC
