### ISSUE TITLE
Linux: Memory usage increasing steadily

### ISSUE THREAD

**Issue by nizarassegaf77** [alexmercerind/dart_vlc#24] opened 2021-04-26 06:27 UTC
I found memory usage continues to increase, until all memory is used, even making device freez. Did I make a mistake or did I add something missing?
I'm run it on linux

**Comment by alexmercerind** [comment] 2021-04-26 06:31
Are you talking about playing a single file or a playlist? Is it a video? Please be little more specific.

**Comment by nizarassegaf77** [comment] 2021-04-26 06:34
i playing a playlist video

**Comment by alexmercerind** [comment] 2021-04-26 06:35
okay. multiple videos in playlist right?

**Comment by nizarassegaf77** [comment] 2021-04-26 06:36
yes

**Comment by DomingoMG** [comment] 2021-04-26 09:25
@alexmercerind @nizarassegaf77 
Could you indicate how much each video weighs? I remember trying to run a 10GB video and it crashed. 😅😅

**Comment by nizarassegaf77** [comment] 2021-04-26 09:34
@DomingoMG i just play some sample video 16mb, but its use almost 2GB memory

**Comment by DomingoMG** [comment] 2021-04-26 09:37
@nizarassegaf77 
What video format is it playing in? .avi, .mp4?

**Comment by nizarassegaf77** [comment] 2021-04-26 09:44
i play .avi .mp4 .ogg .mkv

**Comment by tomassasovsky** [comment] 2021-04-26 22:14
Hey everyone. I too am experiencing a huge memory leak. Having 12GB of RAM on my machine, the example app used up to 10.1GB until it all freezed and I had to reboot my PC. This happened after less than 5 minutes of playing an .mkv that's 651.6 MB.
![Screenshot from 2021-04-26 19-06-01](https://user-images.githubusercontent.com/63405252/116157442-5e8c0400-a6c3-11eb-9472-4d8eb42f2a18.png)

**Comment by alexmercerind** [comment] 2021-04-27 03:35
I suspect that specifically videos would be causing this.
My wrapper does not deallocate the array buffer allocated to a RAW frame (for sending it do Flutter).
Rather it creates a new `uint8_t[]` on the heap, everytime a new frame is extracted. (And that's a big chunk of memory being allocated per frame). 

I'll have a look at this.

**Comment by alexmercerind** [comment] 2021-04-27 17:17
Okay... This is what I've discovered regarding this so far.

The issue is neither with my wrapper neither with Flutter, but at the communication.

I use this function to convert uint8_t[] to flutter's Uint8List. (header).
```cpp
/**
 * fl_value_new_uint8_list:
 * @value: an array of unsigned 8 bit integers.
 * @value_length: number of elements in @value.
 *
 * Creates an ordered list containing 8 bit unsigned integers. The data is
 * copied. The equivalent Dart type is a Uint8List.
 *
 * Returns: a new #FlValue.
 */
FlValue* fl_value_new_uint8_list(const uint8_t* value, size_t value_length);
```
And it says, "The data is copied".
since this is present in a header...
its actual declaration from the source file is... (from https://engine.chinmaygarde.com/fl__value_8cc_source.html, probably personal website of some Google Flutter employee)
```cpp
 G_MODULE_EXPORT FlValue* fl_value_new_uint8_list(const uint8_t* data,
                                                  size_t data_length) {
   FlValueUint8List* self = reinterpret_cast<FlValueUint8List*>(
       fl_value_new(FL_VALUE_TYPE_UINT8_LIST, sizeof(FlValueUint8List)));
   self->values_length = data_length;
   self->values = static_cast<uint8_t*>(g_malloc(sizeof(uint8_t) * data_length));
   memcpy(self->values, data, sizeof(uint8_t) * data_length);
   return reinterpret_cast<FlValue*>(self);
 }
```
and here we can see that the memory actually is being allocated to heap (AND THATS WHY ITS NOT BEING DEALLOCATED after frame callback is completed)...
```cpp
g_malloc(sizeof(uint8_t) * data_length)
```

so this is what is causing this issue... only bad thing is that there is no pointer available to that memory on the heap. So, how can I call `free` on it.

**Comment by alexmercerind** [comment] 2021-04-27 18:41
It is a problem with the implementation in Flutter engine itself... 

So now I used this method (fl_value_get_uint8_list) to get the pointer to internal uint8_t[] allocated dynamically & then i freed it.

free(const_cast<void*>(static_cast<const void*>(fl_value_get_uint8_list(videoFrameByteArray))));

(well well well, thats a lot of casting, and thats again something i cant do anything about)... 
but finally the memory is deallocated... but still i was able to notice it because this chunk is considerably large, think at how many places do i have to call free manually.
and as a result, memory is still climing atleast some slow rate on linux.
and i have to literally dig to the declaration of the method inside Flutter engine to fix this minimal problem.


With that being said, RAM won't climb to GBs in seconds or minutes. But, it will still climb at a very slow rate on Linux.

**Comment by alexmercerind** [comment] 2021-04-27 18:41
This should be fixed after latest commit.

**Closed by alexmercerind** 2021-04-27 18:41 UTC
Labels: bug, critical
